language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
    - sshpass
install:
  - npm install
script:
  - npm run build
after_success: 
  - export SSHPASS=[jiexun407.]
  - scp -P407 -o stricthostkeychecking=no -r ./dist/* jiexun@122.51.136.91:/www
