language: node_js
node_js:
  - "8"
addons:
  ssh_known_hosts:
  - 122.51.136.91
install:
  - npm install
script:
  - npm run build
after_success:
  - ssh-keygen 
  - ssh-copy-id -i ./id_rsa.pub jiexun@122.51.136.91 -p 407
  - scp -P407 -o stricthostkeychecking=no -r ./dist/* jiexun@122.51.136.91:/www
