language: node_js
node_js:
  - "8"
addons:
  ssh_known_hosts:
  - 122.51.136.91
install:
  - npm install
script:
  - npm run build
after_success:
- rsync -az --delete ./dist/* jiexun@122.51.136.91:/www/
